### ISSUE TITLE
Unable to download Chinese subtitle

### ISSUE THREAD

**Issue by haneoto** [AdvMaple/biliintl_subtitle_download_plugin#15]
Unable to generate download links for Chinese subtitles, no problem for other languages.
![2022-1-1 20-29-15](https://user-images.githubusercontent.com/39939317/147850572-e5cbdd2a-9129-47cb-9bee-7bcf8c1db313.png)

**Comment by AdvMaple** [comment]
This problaly mean there isn't Chinese subtitle
Just check it, this is a bug. I will fix this later

**Comment by AdvMaple** [comment]
![image](https://user-images.githubusercontent.com/46006210/147855535-b68936f0-edcc-4fce-8ebb-2a0fdeebbbf4.png)
I fixed it, try update the plugin.

**Comment by haneoto** [comment]
It has been updated, but it still doesn't work.
![2022-1-2 7-28-51](https://user-images.githubusercontent.com/39939317/147862232-f61c2bf7-31fd-41cd-bff9-8429f782305e.png)

**Comment by AdvMaple** [comment]
Can you check whether the option for Chinese sub has value of "zh-Hans" at line 50:
![image](https://user-images.githubusercontent.com/46006210/147872490-a4b31cbf-dccf-4e18-be85-c17c72a806a4.png)

**Comment by haneoto** [comment]
I checked.
![2022-1-2 18-8-39](https://user-images.githubusercontent.com/39939317/147872736-64389482-7c4e-432f-8c00-7bede9dafd60.png)

**Comment by AdvMaple** [comment]
![image](https://user-images.githubusercontent.com/46006210/147873313-269886c4-d154-4c08-8b6a-9a81edc9edfc.png)
Can you recheck the download?
There are a few series that doesn't have Chinese subtitle so it won't generate link. You can confirm that with this api:
https://api.bilibili.tv/intl/gateway/m/subtitle?ep_id=EP_ID

EP_ID is the last few digit at the end of the url: https://www.bilibili.tv/en/play/34613/342548 <- EP_ID

Replace with your EP_ID and check whether it has Chinese sub or not. 

Here there is:
![image](https://user-images.githubusercontent.com/46006210/147873399-3e4663f5-c506-49cc-a7b0-dc600aa9a894.png)

But this isn't:
![image](https://user-images.githubusercontent.com/46006210/147873419-161c937f-3bcc-4112-a44c-d20b1fd44740.png)

**Comment by haneoto** [comment]
I could see the Chinese subtitles, but the plugin just couldn't generate the links.
![2022-1-2 19-1-19](https://user-images.githubusercontent.com/39939317/147873782-b13dbefa-92df-4d43-a676-a27158b3ebb6.png)
![2022-1-2 19-1-55](https://user-images.githubusercontent.com/39939317/147873783-c435b35c-bd9d-4e7a-b713-0f41558fefef.png)

**Comment by AdvMaple** [comment]
Did you try switch to other language then switch back to Chinese?

**Comment by haneoto** [comment]
I tried, but it still didn't work.

If you can't figure out why, forget it.
I can use the above method to download the JSON file and convert it to SRT.
Thank you for your help.
